---
apiVersion: v1
kind: ReplicationController
metadata:
  name: sshd-jumpserver-rc
spec:
  replicas: 1
  selector:
    app: sshd-jumpserver
  template:
    metadata:
      labels:
        app: sshd-jumpserver
    spec:
      containers:
      - name: sshd-jumpserver
        image: carlosedp/ssh-jumpserver:arm64
        ports:
          - containerPort: 22
        volumeMounts:
        - name: authorized-keys
          mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
          readOnly: true
        - name: ssh-config
          mountPath: /root/.ssh/config
          subPath: config
        #env:
        #  - name: PUBLIC_KEY
        #    valueFrom:
        #      secretKeyRef:
        #        name: ssh-authorized-keys
        #        key: authorized_keys
      volumes:
      - name: authorized-keys
        secret:
          secretName: ssh-authorized-keys
      - name: ssh-config
        secret:
          secretName: ssh-config
